### ISSUE TITLE
Requests from the board 

### ISSUE THREAD

**Issue by KellyTee5156** [pgcweb/PGCwebsite#11]
1. On the "Learn to fly page" can we add a line- “Gift certificates can be purchased at the field during normal flying hours, or by contacting Phil Klauder at phil.klauder@verizon.net.” ?
2. On the "Location Page" can we put a reminder "Non-members  are not permitted to land powered planes at PGC"

Thank you all!
Kelly

**Comment by kilokilopgc** [comment]
Hi Kelly … I will let the new web team make all changes going forward … I will only get involved if specifically requested.

Best of luck to you guys … have a fun and safe soaring season …

Ken

**Comment by pgcweb** [comment]
1 has been updated. 2 was already there.
