### ISSUE TITLE
Access to Pilot Data Signoff

### ISSUE THREAD

**Issue by KellyTee5156** [pgcweb/PGCwebsite#12]
I've doing pilot data this year and need administrator access to update records. Thank you!!!

**Comment by pgcweb** [comment]
I have added Kelly to SYSADMIN, not sure that is correct, have emailed Ken. You need to have SYSADMIN access to get to: "ACCESS Admin Menu" ==> "Add members to groups." Verify by searching in "Member Assigned Groups" Note: check in Member assigned groups BEFORE you add to prevent duplicated records. No interface to delete records. Need to go into the database directly to delete.

**Comment by kilokilopgc** [comment]
I’m not exactly sure what you were trying to do based on the message below  … but if you want to remove a person’s assignment to a group … you edit that assignment record and make it inactive … deleting would break the audit trail …

cid:image004.png@01D16AEF.FCB1E520

**Comment by kilokilopgc** [comment]
1/ All apps under the new control system should have these two requires at the top of the code … look at pgc_access_menu.php as an example. 

require_once('pgc_access_save_appname.php'); 

/\* START - PAGE ACCESS CHECKING LOGIC - ADD TO ALL APPS - START */

require_once('pgc_access_app_check.php');

/\* END - PAGE ACCESS CHECKING LOGIC - END */

The first saves the app name to the control table – so you don’t have to enter app names as you create new functions – they are entered automatically at first use.

The second checks the control system to see  if the logged in person has access to that specific app …   1/ they have to be assigned to a group first … 2/ and that group has to be allowed access to that app …

2/ The Group names are arbitrary – you can create any group name you want for any population of PGC members  … I created all those in CAPS … I don’t know who created Schedule / Pilot … I think someone on the BOD …

3/ If the application does not have any assigned groups … any logged in member can access … most of the apps in the members section are like this … 

4/ You can give multiple groups access to an app … so FDADMIN  can be assigned … and  CFIG can be assigned … to an app to allow separate groups to access … you can see who is assigned to group via Member Assigned Groups …

5/ SYSADMIN has access to all apps as a default … it does not have to be specifically entered for each app … however, if SYSADMIN allowed specifically for an app and is the only group assigned – then only SYSADMIN can access that app.

Kelly just needs FDADMIN to access  …. this will allow her to access the Main Field Duty Menu (pgc_fd_menu.php) app … if you look at the Application Assigned Groups screen … available through the Access Control Menu …

This control system is new and replaces the old role based control we started with … that old single level system could not provide the control resolution we need with all the apps in the system.  So, I have been adding this level of control to the apps – and removing the old role controls … this is not completed.

DOCADMIN is Document Library Administration …

MAINTENANCE gives people access to the Maintenance Menu … 

From: Ken [mailto:KILOKILO@verizon.net] 
Sent: Friday, February 19, 2016 8:39 AM
To: 'pgcweb/PGCwebsite'; 'pgcweb/PGCwebsite'
Subject: RE: [PGCwebsite] Access to Pilot Data Signoff (#12)

I’m not exactly sure what you were trying to do based on the message below  … but if you want to remove a person’s assignment to a group … you edit that assignment record and make it inactive … deleting would break the audit trail …

cid:image004.png@01D16AEF.FCB1E520

**Comment by kilokilopgc** [comment]
The old role based control used the ROLE column in the members table …

So people could get ADMIN0 … if they were system administrators … or ADMIN1, ADMIN2 … etc … just some arbitrary level that could be checked when the person  invoked an application.

But, this was all hard coded … I had to include hard code in the app to only allow ADMIN0 levels to access (or even see) the option … this started to break down …

So you may see apps with these ‘ADMIN’ checks … these should be replaced with the new table based group access control as described below … there’s always something to do and learn … enjoy.

**Comment by pgcweb** [comment]
Pilot data manager needs ADMIN access and needs to be added to the PGC_instructors database as a non-instructor. This has been completed.
