### ISSUE TITLE
Upload new member application to "Join PGC Page"

### ISSUE THREAD

**Issue by KellyTee5156** [pgcweb/PGCwebsite#14]
The new app is a fillable form and has my contact info :)
[PGC Membership Application Fillable.pdf](https://github.com/pgcweb/PGCwebsite/files/195758/PGC.Membership.Application.Fillable.pdf)

**Comment by pgcweb** [comment]
completed

**Comment by KellyTee5156** [comment]
The application at the link on the "Join PGC" page  still has Phil's
contact info. The one I attached should have mine. Thanks so much!
