### ISSUE TITLE
Change my email on front page to Kelly.Terefenko@gmail.com 

### ISSUE THREAD

**Issue by KellyTee5156** [pgcweb/PGCwebsite#15]
Thanks! I'm getting rid of my comcast email.

**Comment by pgcweb** [comment]
Unfortunately the button on the front page is a graphic. We need a new graphic to fix it.

**Comment by Basketkase** [comment]
Hi Kelly!

Is this on the new Wordpress home page? Or the original home page?

**Comment by ghost** [comment]
Leo, the graphic is on both.

**Comment by ghost** [comment]
This has been updated
