### ISSUE TITLE
Research Themes for the new website.

### ISSUE THREAD

**Issue by pgcweb** [pgcweb/PGCwebsite#2]
Moving to WordPress, need to select a theme.

**Comment by whiskeytangopgc** [comment]
As a conversation starter attached a sketch of how I could I imagine the new website layout to look like. No mayor changes. I suggest not having the full PGC introduction on our main page but rather just an opener and you can click on it to either expand or go to a new page to read the full text. The background to this opener could be a picture that is regularly updated.
All the other content (web cams, calendar of events) that are of regular interest would move up and immediately into view. 
Also attached how a mobile version may look - I think more and more people use that as their primary way of checking the site.
![img20151128_18252986](https://cloud.githubusercontent.com/assets/16036018/11454543/88b2f48c-95fd-11e5-8225-1b08d5dfdd77.jpg)

**Comment by pgcweb** [comment]
whiskeytango; Go ahead and give it a try.The site is still experimental. Try out some new pages and change the them if you like.

**Comment by whiskeytangopgc** [comment]
Have taken some time to look through Themes and think that GP is a good pick. 
https://generatepress.com/gp-premium/

It is dynamic with good switch over from desktop to mobile, good selection of side bars, footers, header image... and offers an add on package @$40 for more color options, background and header images...
Here a couple screen shots 
![gp_large](https://cloud.githubusercontent.com/assets/16036018/13720314/62acac10-e7d3-11e5-8c5a-10544ab8c530.JPG)
![gp_small](https://cloud.githubusercontent.com/assets/16036018/13720319/723ec082-e7d3-11e5-939e-098624c56fd9.JPG)

**Comment by pgcweb** [comment]
GP looks like a good choice. I have installed the free version. Leo is purchasing the pro version.

**Comment by ghost** [comment]
The Pro version of  GeneratePress has been purchased and installed. Looks great!
