### ISSUE TITLE
Interface between WordPress and PDP

### ISSUE THREAD

**Issue by pgcweb** [pgcweb/PGCwebsite#3]
WordPress has a robust login. We do not what members to have to log into both the WordPress site and the PDP. We need a plugin for WordPress that will allow access to the PDP.

**Comment by ghost** [comment]
The plugin appears to be working, but only at lower level domains. I can set Session variables in the Wordpress directory, but they are not available at the root directory where the Pilot Data Portal need them. close

**Comment by ghost** [comment]
This has been resolved. In part by moving to pgcsoaring.COM, putting WordPress at the root directory and creating a subdomains php.pgcsoaring.com.  Code for plugin follows: 
<?php
/*
- Plugin Name: PGC_PDP_setcookie
- Plugin URI: http://www.quovadimus.net
- Descripton: This plugin bridges between WordPress and PGC PDP
- Author: Dave Johnson
- Version: 0.2
- Author URI: saywhat
  *License: GPLv2 or later

Copyright (C) 2015 - Quovadimus 

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

 need to add action after login look it up
*/ 
add_action('init', 'PGCstartSession', 1);
add_action('wp_logout', 'PGCpdpLogout');
add_action('wp_login', 'PGCpdpLogin', 10 , 2); 

function PGCpdpLogin($user_login, $user) {
   global $username_PGC;
   global $password_PGC;
   global $database_PGC;
   global $hostname_PGC;
   session_start(); 
  if (!isset($_SESSION['MM_Username'])) {
    include($_SERVER['DOCUMENT_ROOT'].'../../Connections/PGC.php');
    $_SESSION['MM_Username'] = $user->user_email ;
// use pilot name from PDP database, for now to simplify maintenance. 
//   $_SESSION['MM_PilotName'] = $user->user_lastname . ", " .  $user->user_firstname; 
 // create new wp db object pointing to PDP database 
  $pgc_db = new wpdb($username_PGC, $password_PGC, $database_PGC , $hostname_PGC);  
    $pgc_db->show_errors();
    $pgc_user_data = $pgc_db->get_results("SELECT NAME, ROLE, duty_role, active FROM pgc_members WHERE USER_ID='$user->user_email'");
   if ($pgc_db->num_rows == 1) {
      if ($pgc_user_data[0]->active == 'YES') {
         //declare session variables and assign them  
             $_SESSION['MM_PilotName'] =  $pgc_user_data[0]->NAME; 
         $_SESSION['MM_PilotRole'] =  $pgc_user_data[0]->ROLE; 
         $_SESSION['MM_duty_role'] =  $pgc_user_data[0]->duty_role; 
         $_SESSION['MM_LoginToken'] =  rand(); //?  
      }  
     } 
    session_write_close();
  }
}
function PGCstartSession()
 {
  if (!session_id()) {
    session_start();
  }
}
function PGCpdpLogout(){
    session_start();
    session_destroy();  
}
