### ISSUE TITLE
Update Membership chair on website to Kelly

### ISSUE THREAD

**Issue by whiskeytangopgc** [pgcweb/PGCwebsite#9]

**Comment by kilokilopgc** [comment]
I updated the main page button in Photoshop ... so the graphic look/feel will be the same ...  can you guys update any of the other items ... replacing Matt's contact E-mail for Kelly's ... KK

**Comment by kilokilopgc** [comment]
From: Kelly Terefenko [mailto:kellyanne5156@gmail.com] 
Sent: Saturday, December 12, 2015 7:45 AM
To: Ken
Subject: Re: Membership Contact E-Mail

Can we give them my Comcast (Kelly.Terefenko@comcast.net) ?

**Comment by whiskeytangopgc** [comment]
I will update it.
Ken,
how do I access the content of our current website so I can familiarize myself and make changes?

**Comment by kilokilopgc** [comment]
You need a page editor – do you have one?

I use Dreamweaver … but some people like this free alternative for PCs …

https://www.microsoft.com/en-us/download/details.aspx?id=36179

**Comment by pgcweb** [comment]
Updated Mail to 18 Dec 2015 Magic
